name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Publish
      run: |
        dotnet publish app/GHelper.sln --configuration Release --runtime win-x64 -p:PublishSingleFile=true --self-contained true
    - name: Upload unsigned EXE
      id: upload-unsigned
      uses: actions/upload-artifact@v4
      with:
        path: app/bin/x64/Release/net8.0-windows/win-x64/publish/GHelper.exe